### PR TITLE
Fixed avx2_backend by updating dependencies

### PR DESCRIPTION
**Pull request by vkomenda**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
lgtm as long as the CI checks pass :)

**Comment by ghost** [comment]
@vkomenda on further investigation, it turned out dalek3 breaks our wasm build: the following command fails:
`cargo +nightly build --target wasm32-unknown-unknown --no-default-features --features no_std --features u32_backend`

So we should probably fork dalek as well, change the dependency to simd in V2 and then change our fork of bulletproofs and schorrkel

Or we need to investigate and fix the problem with wasm and dalek v3

**Comment by vkomenda** [comment]
> @vkomenda on further investigation, it turned out dalek3 breaks our wasm build: the following command fails:
> `cargo +nightly build --target wasm32-unknown-unknown --no-default-features --features no_std --features u32_backend`
> 
> So we should probably fork dalek as well, change the dependency to simd in V2 and then change our fork of bulletproofs and schorrkel
> 
> Or we need to investigate and fix the problem with wasm and dalek v3

It builds OK, just omit `no_std`:
```
cargo +nightly build --target wasm32-unknown-unknown --no-default-features --features u32_backend
```

**Comment by vkomenda** [comment]
Regarding the failing CI check, this PR is based on the `devel` branch which only compiles with nightly. Do we need stable anywhere?

**Comment by ghost** [comment]
nope, we don't need stable.

**Comment by ParnianAlimi** [comment]
No tasks are mentioned for this PR and it doesn't have a description; I can't really follow what's happening. Also Dalek might not support `avx2_backend` in the long run, see this comment: https://github.com/dalek-cryptography/curve25519-dalek/blob/3.0.0/Cargo.toml#L63.

**Pull request closed without merging**
